### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by harunemre** [iron9light/HOCON.Json#3]
Hello. I'm glad that you contributed the hocon for .net.

I'm trying to map an object class to hocon config. Can you show if it is possible? 

Example:

```
public class MyConfigClass
{
  public string Version {get; set;}
  public bool SomeBool {get; set;} 
  public string AppName {get; set;} 
  public int SomeId {get; set;} 
  public string[] SomeArray {get; set;} 
...
}

/* ***************************
* when writing the config to file
******************************/

var myconfig = new MyConfigClass()
{
Version = "1.0.1",
SomeBool = true,
AppName = "MyApp",
SomeId = 50932,
SomeArray = ["eeny", "meeny", "miny", "moe"]
};

var hoconConfigString = Hocon.Serialize(myconfig); // prettyPrint

File.WriteAllText(@"mypath\myconfig.cfg", myconfig )

/* ***************************
* when reading the config from file
******************************/

var hoconConfigString = File.ReadAllText("@"mypath\myconfig.cfg");

MyConfigClass mcc = Hocon.Serialize<MyConfigClass>(hoconConfigString);



```

**Comment by iron9light** [comment]
1. This project is not HOCON for dotnet, it's just an extension. So you should ask this feature [here](https://github.com/akkadotnet/HOCON)
2. HOCON is designed for config only. But JSON is more general data format, it can be use for object Serialization.
3. If you really wanna serialize an object to HOCON, just serialize it as JSON, since HOCON is a superset of JSON.
4. If you wanna deserialize, you can use HOCON.JSON to convert to JSON first and then deserialize it.

Wish these hints work for you.
